version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - '80:80'
      - '443:443'
    environment:
      - CADDY_INGRESS_NETWORKS=$MY_DOCKER_NETWORK
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/data:/data

networks:
  default:
    name: $MY_DOCKER_NETWORK
    external: true
