name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate env from secrets
        run: (echo "MY_DOMAIN=${{ secrets.MY_DOMAIN }}\n"; cat .env) > .full_env && mv .full_env .env

      - name: Add the host key
        run: |
          mkdir -p ~/.ssh/ && echo "${{ secrets.DEPLOY_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Atomic Deploy
        run: |
          ssh ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} -p ${{ secrets.DEPLOY_PORT }} << EOF
            # Enter the main directory
            cd ${{ secrets.DEPLOY_FILE_PATH }} 
            # On first run clone the repo
            [ ! -d "./homelab" ] && ssh-keyscan -H github.com > ~/.ssh/known_hosts && git clone git@github.com:ImLunaHey/homelab.git homelab
            # Enter project directory
            cd homelab
            # Make sure the install it up to date
            git pull
            # Reload services
            ./.scripts/env.sh && docker compose up -d
          EOF