name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate env from secrets
        run: (echo "MY_DOMAIN=${{ secrets.MY_DOMAIN }}\n"; cat .env) > .full_env && mv .full_env .env

      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Atomic Deploy
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            cd ${{ secrets.DEPLOY_FILE_PATH }} && (git -C homelab pull || git clone git@github.com:ImLunaHey/homelab.git) && ./.scripts/env.sh && docker compose up -d
          EOF