name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Generate env from secrets
        run: (echo "MY_DOMAIN=${{ secrets.MY_DOMAIN }}\n"; cat .env) > .env

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: cd ${{ secrets.DEPLOY_FILE_PATH }} && (git -C homelab pull || git clone git@github.com:ImLunaHey/homelab.git) && ./.scripts/env.sh && docker compose up -d